# DIVA-SQL Configuration

# LLM Settings
DEFAULT_MODEL = "gpt-4"
MAX_ITERATIONS = 3
CONFIDENCE_THRESHOLD = 0.7
TEMPERATURE = 0.1

# Pipeline Settings
ENABLE_CACHING = True
PARALLEL_VERIFICATION = False
MAX_NODES_PER_DAG = 10

# Evaluation Settings
BENCHMARK_TIMEOUT = 30  # seconds
SAVE_INTERMEDIATE_RESULTS = True
ENABLE_DETAILED_LOGGING = True

# Database Settings
DEFAULT_DATABASE_TYPE = "sqlite"
CONNECTION_TIMEOUT = 10

# Error Taxonomy Settings
ENABLE_PATTERN_MATCHING = True
HIGH_SEVERITY_THRESHOLD = 0.8
MEDIUM_SEVERITY_THRESHOLD = 0.5

# Human Study Settings
MIN_PARTICIPANTS = 10
TASK_TIMEOUT = 300  # seconds
RANDOMIZE_ORDER = True
